Content:
    Golem:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: "GOLEM"
        home: https://ajacquey.github.io/golem/index.html
        repo: https://github.com/ajacquey/golem
        menu:
            Getting Started: getting_started/index.md
            Examples: examples/examples.menu.md
            Manuals: manuals/manuals.menu.md
            Documentation: documentation/documentation.menu.md
            Help: help/help.menu.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
    
